server:
  port: 8010

user:
  userServiceUrl: http://localhost:8080/

spring:
  application:
    name: microservice-consumer-movie-ribbon-hystrix

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true